apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfyui
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: comfyui
  template:
    metadata:
      labels:
        app: comfyui
    spec:
      runtimeClassName: nvidia
      tolerations:
        - key: "nvidia.com/gpu"
          operator: Exists
          effect: NoSchedule
      terminationGracePeriodSeconds: 0
      containers:
        - name: comfyui
          image: {{ .Values.image }}
          ports:
            - containerPort: 8188
          env:
            - name: SERVICEPORTAL_URL
              value: https://{{ .Values.domain }}
            - name: SERVICENAME_URL
              value: https://{{ .Values.domain }}
            - name: COMFYUI_URL
              value: https://{{ .Values.domain }}
          resources:
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - mountPath: /root
              name: root-volume
            - mountPath: /root/ComfyUI/models
              name: models-volume
            - mountPath: /root/.cache/huggingface/hub
              name: hf-cache-volume
            - mountPath: /root/.cache/torch/hub
              name: torch-cache-volume
            - mountPath: /root/ComfyUI/input
              name: input-volume
            - mountPath: /root/ComfyUI/output
              name: output-volume
            - mountPath: /root/ComfyUI/user/default/workflows
              name: workflows-volume
      volumes:
        - name: root-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-root-pvc
        - name: models-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-models-pvc
        - name: hf-cache-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-hf-cache-pvc
        - name: torch-cache-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-torch-cache-pvc
        - name: input-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-input-pvc
        - name: output-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-output-pvc
        - name: workflows-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-workflows-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: comfyui-svc
spec:
  type: ClusterIP
  selector:
    app: comfyui
  ports:
  - name: http
    port: 8188
    protocol: TCP
    targetPort: 8188