apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-input-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: nfs-fast
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
