baseDomain: arr.homelab.seifert.id

jellyfin:
  image: jellyfin/jellyfin:10.11.0-rc3

overseerr:
  image: fallenbagel/jellyseerr:latest

flaresolverr:
  image: ghcr.io/flaresolverr/flaresolverr:latest

prowlarr:
  image: lscr.io/linuxserver/prowlarr:latest

radarr:
  image: lscr.io/linuxserver/radarr:latest

sonarr:
  image: lscr.io/linuxserver/sonarr:latest
